<<<<<<<< HEAD:.github/workflows/dev-docker-image.yml
name: dev-api-mipo-msk-ru

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
========
name: prod-api-mipo-msk-ru

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
>>>>>>>> 6555a5aa7da86282487486462ff010a4594b4b00:.github/workflows/prod-docker-image.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Customization of SHA up to 7 characters 
        run: echo "GITHUB_SHA_CUSTOMIZE=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
<<<<<<<< HEAD:.github/workflows/dev-docker-image.yml
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev-api-mipo-msk-ru:${{ env.GITHUB_SHA_CUSTOMIZE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-api-mipo-msk-ru:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-api-mipo-msk-ru:buildcache,mode=max
========
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/prod-api-mipo-msk-ru:${{ env.GITHUB_SHA_CUSTOMIZE }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/prod-api-mipo-msk-ru:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/prod-api-mipo-msk-ru:buildcache,mode=max
>>>>>>>> 6555a5aa7da86282487486462ff010a4594b4b00:.github/workflows/prod-docker-image.yml

